import { HealthyState } from './healthy-types';

export const HEALTHY_SEED: HealthyState = {
  siteName: 'Healthy Time | وقت الصحة',
  logoText: 'HT',
  packages: [
    {
      id: 'pkg-chicken-24',
      name: 'اشتراك دجاج 24 يوم',
      category: 'chicken',
      days: 24,
      mealsPerDay: 2,
      snacksPerDay: 1,
      price: 2200,
      description: 'خطة دجاج يومية متوازنة ومناسبة لبناء العضلات.',
      active: true,
      displayOrder: 1,
    },
    {
      id: 'pkg-mixed-24',
      name: 'اشتراك منوع 24 يوم',
      category: 'mixed',
      days: 24,
      mealsPerDay: 2,
      snacksPerDay: 1,
      price: 2600,
      description: 'تنوع صحي يومي بين الدجاج واللحوم والأسماك.',
      active: true,
      displayOrder: 2,
    },
    {
      id: 'pkg-mixed-plus-30',
      name: 'اشتراك منوع بلس شهري',
      category: 'mixed_plus',
      days: 30,
      mealsPerDay: 3,
      snacksPerDay: 2,
      price: 3700,
      description: 'باقة بلس بعدد وجبات أعلى وخيارات أوسع.',
      active: true,
      displayOrder: 3,
    },
  ],
  meals: [
    {
      id: 'meal-1',
      nameAr: 'دجاج مشوي مع أرز بني',
      nameEn: 'Grilled Chicken with Brown Rice',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200',
      tags: ['chicken', 'mixed', 'mixed_plus'],
      subscriptionEligible: true,
      buffetEligible: true,
      buffetPrice: 35,
      calories: 520,
      protein: 45,
      carbs: 48,
      fat: 14,
      weightGrams: 360,
      description: 'وجبة متوازنة عالية البروتين.',
      ingredients: 'دجاج، أرز بني، خضار موسمية.',
      allergens: 'لا يوجد',
      available: true,
      displayOrder: 1,
    },
    {
      id: 'meal-2',
      nameAr: 'سلمون مع كينوا',
      nameEn: 'Salmon with Quinoa',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200',
      tags: ['mixed', 'mixed_plus'],
      subscriptionEligible: true,
      buffetEligible: false,
      calories: 570,
      protein: 38,
      carbs: 42,
      fat: 22,
      weightGrams: 340,
      description: 'أوميغا 3 مع مصدر كارب معقد.',
      ingredients: 'سلمون، كينوا، سبانخ.',
      allergens: 'أسماك',
      available: true,
      displayOrder: 2,
    },
    {
      id: 'meal-3',
      nameAr: 'ساندوتش ديك رومي صحي',
      nameEn: 'Lean Turkey Sandwich',
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200',
      tags: ['mixed_plus', 'snack'],
      subscriptionEligible: true,
      buffetEligible: true,
      buffetPrice: 20,
      calories: 290,
      protein: 22,
      carbs: 30,
      fat: 8,
      weightGrams: 220,
      description: 'سناك بروتيني خفيف.',
      ingredients: 'خبز حبوب كاملة، ديك رومي، خس.',
      allergens: 'جلوتين',
      available: true,
      displayOrder: 3,
    },
  ],
  customers: [
    {
      id: 'cus-1',
      name: 'سارة العتيبي',
      phone: '0500000001',
      email: 'sara@example.com',
      packageId: 'pkg-mixed-24',
      days: 24,
      mealsPerDay: 2,
      snacksPerDay: 1,
      startDate: '2026-04-10',
      endDate: '2026-05-05',
      specialNotes: 'تفضل وجبات منخفضة الملح.',
      allergies: 'أسماك',
      forbiddenFoods: 'فلفل حار',
      address: 'الرياض - حي الندى',
      locationUrl: 'https://maps.google.com',
      status: 'active',
      internalNotes: 'تتواصل عبر واتساب.',
      usedDays: 8,
      selectedMeals: 14,
      selectedSnacks: 6,
      token: 'sara-healthy-time',
      tokenActive: true,
    },
  ],
  orders: [
    {
      id: 'ord-1',
      customerId: 'cus-1',
      date: '2026-04-22',
      meals: ['meal-1', 'meal-2'],
      snack: 'meal-3',
      notes: 'بدون صوص.',
      allergy: 'أسماك',
      deliveryTime: '14:00',
      status: 'in_preparation',
    },
  ],
  notices: [
    {
      id: 'n-1',
      target: 'customer',
      customerId: 'cus-1',
      title: 'اختر وجباتك',
      body: 'لا تنس اختيار وجبات يوم غد قبل الساعة 10 مساءً.',
      createdAt: '2026-04-22T08:00:00.000Z',
    },
    {
      id: 'n-2',
      target: 'admin',
      title: 'عميل لم يختر وجباته',
      body: 'سارة العتيبي لم تكمل اختيارات أسبوعها القادم.',
      createdAt: '2026-04-22T08:05:00.000Z',
    },
  ],
};
